# Generated by Django 4.2.11 on 2024-05-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='yougenerated_content',
            new_name='generated_content',
        ),
    ]
